# Generated by Django 4.2.7 on 2023-12-19 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('subject', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, null=True)),
                ('conclusion', models.TextField(blank=True, null=True)),
                ('show_payment', models.BooleanField(default=True)),
                ('signed', models.BooleanField(default=False)),
                ('unlock', models.BooleanField(default=True)),
                ('raise_by', models.ForeignKey(default='99078', on_delete=django.db.models.deletion.CASCADE, related_name='raised_by', to='hr.employee')),
                ('submitted_to', models.ForeignKey(default='99090', on_delete=django.db.models.deletion.CASCADE, related_name='submiited_to', to='hr.employee')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MeasuringUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PartItem',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('part_no', models.CharField(blank=True, max_length=50, null=True)),
                ('rev_part', models.CharField(blank=True, max_length=50, null=True)),
                ('part_name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('item_type', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='management.itemtype')),
                ('unit', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.measuringunit')),
            ],
            options={
                'ordering': ['id', 'part_no', 'part_name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('subject', models.CharField(max_length=200)),
                ('recommendation', models.TextField()),
                ('pay_to_company', models.BooleanField(default=False)),
                ('advance', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('security', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('received_on', models.DateField()),
                ('raise_by', models.ForeignKey(default='99078', on_delete=django.db.models.deletion.CASCADE, related_name='payment_raised_by', to='hr.employee')),
                ('submitted_to', models.ForeignKey(default='99090', on_delete=django.db.models.deletion.CASCADE, related_name='payment_submiited_to', to='hr.employee')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentOthers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('subject', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, null=True)),
                ('conclusion', models.TextField(blank=True, null=True)),
                ('signed', models.BooleanField(default=False)),
                ('raise_by', models.ForeignKey(default='99078', on_delete=django.db.models.deletion.CASCADE, related_name='others_raised_by', to='hr.employee')),
                ('submitted_to', models.ForeignKey(default='99090', on_delete=django.db.models.deletion.CASCADE, related_name='others_submiited_to', to='hr.employee')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('order_by', models.ForeignKey(default='99078', on_delete=django.db.models.deletion.CASCADE, to='hr.employee')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('reference', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField()),
                ('advance_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('security_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('vat_deducted', models.BooleanField(default=False)),
                ('ait_deducted', models.BooleanField(default=True)),
                ('selected', models.BooleanField(default=True)),
                ('approval', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.approval')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TermText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('text', models.TextField()),
            ],
            options={
                'ordering': ['title', 'text'],
            },
        ),
        migrations.CreateModel(
            name='TitleItem',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('item', models.TextField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('bin', models.CharField(blank=True, max_length=25, null=True)),
                ('tin', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VendorContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('mobile', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.vendor')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VendorAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(max_length=200)),
                ('district', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='management.vendor')),
            ],
            options={
                'ordering': ['district', 'address'],
            },
        ),
        migrations.CreateModel(
            name='VendorAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('number', models.CharField(max_length=50)),
                ('routing', models.CharField(max_length=12)),
                ('bank', models.CharField(blank=True, max_length=50, null=True)),
                ('branch', models.CharField(blank=True, max_length=50, null=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.vendor')),
            ],
            options={
                'ordering': ['name', 'bank'],
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('approval', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.approval')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=0, default=1, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('vat', models.DecimalField(decimal_places=2, default=7.5, max_digits=15)),
                ('ait', models.DecimalField(decimal_places=2, default=3.0, max_digits=15)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.partitem')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.quotation')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='quotation',
            name='contact',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.vendorcontact'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='item_type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='management.itemtype'),
        ),
        migrations.CreateModel(
            name='PurchaseOrderTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legend', models.CharField(blank=True, max_length=100, null=True)),
                ('newtext', models.TextField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.purchaseorder')),
                ('text', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='management.termtext')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.quotation'),
        ),
        migrations.CreateModel(
            name='PaymentOthersItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=200, null=True)),
                ('quantity', models.DecimalField(decimal_places=0, default=1, max_digits=10)),
                ('price', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('vat', models.DecimalField(decimal_places=3, default=0.0, max_digits=15)),
                ('ait', models.DecimalField(decimal_places=3, default=5.0, max_digits=15)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.partitem')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.paymentothers')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='paymentothers',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.vendor'),
        ),
        migrations.CreateModel(
            name='PaymentNoteInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=25)),
                ('date', models.DateField()),
                ('particular', models.TextField(max_length=350)),
                ('amount', models.FloatField(default=0.0, max_length=13)),
                ('remark', models.CharField(blank=True, max_length=250, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.paymentnote')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.vendor')),
            ],
            options={
                'ordering': ['id', 'number'],
            },
        ),
        migrations.CreateModel(
            name='PaymentNoteApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.approval')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.paymentnote')),
            ],
        ),
        migrations.AddField(
            model_name='paymentnote',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.vendor'),
        ),
        migrations.CreateModel(
            name='ItemInTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(blank=True, max_length=200, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.titleitem')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.title')),
            ],
        ),
    ]
