# Generated by Django 4.2.7 on 2024-03-27 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_quotationitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendoraccount',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='management.vendor'),
        ),
        migrations.AlterField(
            model_name='vendoraddress',
            name='vendor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='management.vendor'),
        ),
        migrations.AlterField(
            model_name='vendorcontact',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='management.vendor'),
        ),
    ]
