# Generated by Django 4.2.7 on 2024-03-27 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_vendoraccount_vendor_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Title',
            new_name='TitleQuote',
        ),
    ]
