# Generated by Django 4.2.7 on 2024-03-27 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_rename_title_titlequote'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemInTitle',
            new_name='TitleQuoteItem',
        ),
    ]
