# Generated by Django 4.2.7 on 2024-04-03 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_rename_itemintitle_titlequoteitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentnote',
            name='signed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='paymentnoteinvoice',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='management.paymentnote'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='approval',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quotation', to='management.approval'),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='management.quotation'),
        ),
        migrations.AlterField(
            model_name='titlequote',
            name='approval',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='title', to='management.approval'),
        ),
    ]
