# Generated by Django 4.2.7 on 2024-04-03 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_alter_paymentnote_signed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentnote',
            name='signed',
        ),
    ]
