# Generated by Django 4.2.7 on 2024-04-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_remove_paymentnote_signed'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentnote',
            name='signed',
            field=models.BooleanField(default=False),
        ),
    ]
