# Generated by Django 4.2.7 on 2024-04-08 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_paymentnote_signed'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentnote',
            name='ait_percent',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='paymentnote',
            name='vat_percent',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
    ]
