# Generated by Django 4.2.7 on 2024-04-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_paymentnote_ait_percent_paymentnote_vat_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentnote',
            name='vatait_added',
            field=models.BooleanField(default=True),
        ),
    ]
